
// This file was auto-generated by ML.NET Model Builder. 

using Sentiment_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
Sentiment.ModelInput sampleData = new Sentiment.ModelInput()
{
    Col0 = @"Not Tasty.",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Col1 with predicted Col1 from sample data...\n\n");


Console.WriteLine($"Col0: {@"This restaurant was wonderful."}");
Console.WriteLine($"Col1: {0F}");


var sortedScoresWithLabel = Sentiment.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

